before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: DyW6rYOGL/m/FQyyOBedgu4S0y4Ji17UuhEcVKjPZYYaqESxC+/TPCACNXI2UmZ9YPSQNoYTZpdKjFWQ6WeHZYLBFLQUdqp7hJ4FTzPkS5Bwl8/XG6Nl+WD5X16h7/9N1CNKsF39JCj/scjvohJoIMHaKnVzkL+Prd/fcVILVwMeTH5OQ1WdFq+cMghaZ7Hl6nx34JUWO6yiyVQsyCIq4ErnfMkAVN3v7oAWTzi6dzL6nyrSU2tC3qsKZT346G12Kng2pgBB8uA9UUxn9vrQ6qN4zJ8+z8RWRUuvMF063g8JiL8422lysXbNQhUuJamOGOkhjZYy8QVTxP/TC2M9ILg+gl+NWEOMcy7Stfl9xLRbWUNz9QjMCiVrYZUlK+Z3dMTN6XcHEZ0V+sRUcGkz211c70sA8Yii1s7PhbF4tUKDBAHE71p6p/x1ypB72uB5RzymVcV6TxaOuOTpvas2oNzWJ8JaxnpDrI2cbsZnfcUZclli7DI/3kn9XowynPqqoAxBizORo/I1Pt0kKt9HlezePMHkOMy2x0THAmT7e0nyknAg0gJLcBayyPPvIMpwUmdpkHjBGBVjp7osSLiNsl9LqqE/8H6613DZXaczY4vDmqqZhIsN8P//60LrrgA4dit5g85+r7aNQNsrZ7oNECA4boB6UOehknEOnbSmt6s= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
